name: Students CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout repository
      - uses: actions/checkout@v3

      # Step 2: Setup Java 17
      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      # Step 3: Build Maven project
      - name: Build with Maven
        run: mvn clean package -DskipTests

      # Step 4: Build Docker image
      - name: Build Docker image
        run: docker build -t student-service .

      # Step 5: Deploy to Render
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.srv-d4k4hebuibrs73f88od0 }}
          api-key: ${{ secrets.projectstudent }}
